departments/urls.py
from django.urls import path

from .views import *

urlpatterns = [
    path('employees/', employees, name='employees'),
    path('autocomplete/', EmployeesAutocomplete.as_view(), name='autocomplete'),
    path('employees/<int:id>/', employees_profile, name='employee_profile'),
    path('employees/update/<int:emp_id>/del_department/<int:dep_id>/', department_delete, name='department_delete'),
    path('departments/', departments, name='departments'),
    path('departments/create/', DepartmentsCreate.as_view(), name='departments_create'),
    path('departments/update/<int:dep_id>/add_employee/<int:emp_id>/', add_employee, name='add_employee'),
    path('departments/update/<int:id>/', DepartmentsUpdate.as_view(), name='departments_update'),
    path('departments/<int:id>/', departments_profile, name='department_profile'),
    path('', index, name='index'),
]

spbstu/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('departments.urls')),
]

departments/models.py
from django.db import models
from geo.models import City

class Department(models.Model):
    '''Отдел'''
    name = models.CharField(max_length=100, unique=True, verbose_name="Название отдела")
    description = models.TextField(max_length=260, default='', verbose_name="Краткое описание об отделе")

    def __str__(self):
        return self.name

class Employee(models.Model):
    '''Сотрудник'''
    first_name = models.CharField(max_length=100, verbose_name="Имя работника")
    last_name = models.CharField(max_length=100, verbose_name="Фамилия работника")
    age = models.IntegerField()
    description = models.TextField(max_length=260, default='', verbose_name="Краткое описание о работнике")
    city = models.ForeignKey(City, on_delete=models.CASCADE)
    department = models.ForeignKey(Department, null=True, blank=True, on_delete=models.SET_NULL)

    def __str__(self):
        return 'f_name: {} l_name: {} age: {} city: {} department: {}'.format(self.first_name, self.last_name, self.age, self.city, self.department)

geo/models.py
from django.db import models

class Country(models.Model):
    '''Cтрана'''
    name = models.CharField(max_length=100, verbose_name="Название страны")

    def __str__(self):
        return self.name

class City(models.Model):
    '''Город'''
    name = models.CharField(max_length=100, verbose_name="Название города")
    country = models.ForeignKey(Country, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

departments/forms.py
from django import forms
from .models import Department, Employee
from django.core.exceptions import ValidationError
from dal import autocomplete

class DepartmentForm(forms.ModelForm):
    class Meta:
        model = Department
        fields = ['name', 'description']

        widgets = {
            'name': forms.TextInput(attrs={'class':'form-control'}),
            'description': forms.Textarea(attrs={'class':'form-control'}),
        }

class EmployeeAutocompleteForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = ['first_name']

        widgets = {
            'first_name': forms.TextInput(attrs={'class':'form-control'}),
        }

departments/views.py
from django.shortcuts import render, HttpResponse, get_object_or_404, redirect
from .models import Employee, Department
from .forms import DepartmentForm, EmployeeAutocompleteForm
from django.http import Http404
from django.views.generic import View
from dal import autocomplete
from django.db.models import Q

def index(request):
    return render(request, 'index.html', context={})

def employees(request):
    employees = Employee.objects.all
    return render(request, 'employees.html', context={'employees':employees})

def employees_profile(request, id):
    profile = get_object_or_404(Employee, id=id)
    return render(request, 'employee_profile.html', context={
        'department':profile.department,
        'full_name':'{} {}'.format(profile.first_name, profile.last_name),
        'age':profile.age,
        'description':profile.description,
    })

class EmployeesAutocomplete(autocomplete.Select2QuerySetView):
    def get_queryset(self):
        qs = Employee.objects.all()

        if self.q:
            qs = qs.filter(
                Q(first_name__istartswith=self.q)|
                Q(last_name__istartswith=self.q)|
                Q(age__istartswith=self.q)|
                Q(city__name__istartswith=self.q)|
                Q(department__name__istartswith=self.q)
            )

        return qs

def add_employee(request, dep_id, emp_id):
    employee = Employee.objects.filter(id=emp_id).update(department_id=dep_id)
    return redirect('departments_update', dep_id)

def department_delete(request, emp_id, dep_id):
    employee = Employee.objects.filter(id=emp_id).update(department=None)
    return redirect('departments_update', dep_id)

class DepartmentsCreate(View):
    template = 'departments_create.html'

    def get(self, request):
        form = DepartmentForm()

        return render(request, self.template, context={
            'form':form,
        })

    def post(self, request):
        bound_form = DepartmentForm(request.POST)

        if bound_form.is_valid():
            new_department = bound_form.save()
            return redirect('department_profile', new_department.id)
        return render(request, self.template, context={
            'form':bound_form,
        })

class DepartmentsUpdate(View):
    template = 'departments_update.html'

    def get_department(self, id):
        return get_object_or_404(Department, id=id)

    def get(self, request, id):
        department = self.get_department(id)
        form = DepartmentForm(instance=department)
        autocomplete_form = EmployeeAutocompleteForm()

        return render(request, self.template, context={
            'department':department,
            'form':form,
            'autocomplete_form':autocomplete_form,
        })

    def post(self, request, id):
        department = self.get_department(id)
        bound_form = DepartmentForm(request.POST, instance=department)

        if bound_form.is_valid():
            update_department = bound_form.save()
            return redirect('department_profile', update_department.id)
        return render(request, self.template, context={
            'form':bound_form,
        })


def departments(request):
    departments = Department.objects.all()
    return render(request, 'departments.html', context={'departments':departments})

def departments_profile(request, id):
    profile = get_object_or_404(Department, id=id)
    return render(request, 'department_profile.html', context={'department_profile':profile})

geo/views.py
from django.shortcuts import render

# Create your views here.

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
    <head>
    <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <link rel="stylesheet" href="{% static 'css/base_style.css' %}">
        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

        <title>Department</title>
    </head>
    <body class="d-flex flex-column h-100">
        <header>
            <!-- Fixed navbar -->
            <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item active">
                            <a class="nav-link" href="{% url 'index' %}">Home <span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'employees' %}">Employees</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'departments' %}">Departments</a>
                        </li>
                    </ul>
                </div>
            </nav>
        </header>
        <main role="main" class="flex-shrink-0">
            <div class="container">
                {% block content %}
                {% endblock %}
            </div>
        </main>
        <footer class="footer mt-auto py-3">
            <div class="container">
                <span class="text-muted">Place sticky footer content here.</span>
            </div>
        </footer>
        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
        <script src="{% static 'js/form.js' %}"></script>
    </body>
</html>

templates/department_profile.html
{% extends "base.html" %}

{% block content %}
    <h1 class="mt-5">{{ department_profile.name }}</h1>
    <a href="{% url 'departments_update' department_profile.id %}">изменить</a>
    <hr>
    <p class="lead"><code>Description:</code> {{department_profile.description }}</p>
    <p class="lead"><code>Employees:</code></p>
    {% for employee in department_profile.employee_set.all %}
        <p class="lead"><a href="{% url 'employee_profile' employee.id %}">{{ employee.first_name }}</a></p> 
    {% endfor %}
{% endblock %}

templates/departments.html
{% extends "base.html" %}

{% block content %}
    <h1 class="mt-5">Отделы</h1>
    <a href="{% url 'departments_create' %}">Создать новый отдел</a>
    <hr>
    <div class="row">
        {% for department in departments %}
            <div class="col-sm-4">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">{{ department.name }}</h5>
                        <p class="card-text">{{ department.description }}</p>
                        <a href="{% url 'department_profile' department.id %}" class="btn btn-primary">Перейти в профиль отдела</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

templates/departments_create.html
{% extends "base.html" %}

{% block content %}
    <h1 class="mt-5">Создание отдела</h1>
    <form class="form-signin" action="{% url 'departments_create' %}" method="POST">
        {% csrf_token %}

        {% for field in form %}
            <div class="form-group">
                {% if field.errors %}
                    <div class="alert alert-danger">
                        {{ field.errors }}
                    </div>
                {% endif %}

                {{ field.label_tag }}
                {{ field }}
            </div>
        {% endfor %} 

        <button type="submit" class="btn btn-primary">Создать</button>
    </form>
{% endblock %}

templates/departments_update.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <h1 class="mt-5">Изменение отдела</h1>
    <div class="row">
        <div class="col-sm-4">
            <form class="" action="{% url 'departments_update' department.id %}" method="POST">
                {% csrf_token %}

                {% for field in form %}
                    <div class="form-group">
                        {% if field.errors %}
                            <div class="alert alert-danger">
                                {{ field.errors }}
                            </div>
                        {% endif %}

                        {{ field.label_tag }}
                        {{ field }}
                    </div>
                {% endfor %} 

                <button type="submit" class="btn btn-primary">Изменить</button>
            </form>
        </div>
        <div class="col-sm-8">
            <p>Список работников:</p>
            <div>
                <form action="" method="post">
                    {% csrf_token %}
                    <div id="add_employee">
                        {{ autocomplete_form }}
                        <ul id="autocomplete_select" class="list-group" style="display:none">
                        </ul>
                    </div>
                </form>
            </div>
            <hr>
            <ul class="list-group">
                {% for employee in department.employee_set.all %}
                    <li class="list-group-item d-flex justify-content-between align-items-center">
                        <a href="{% url 'employee_profile' employee.id %}">{{ employee.first_name }}</a>
                        <a href="{% url 'department_delete' emp_id=employee.id dep_id=department.id %}"><span class="badge badge-primary badge-pill">x</span></a> 
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>

{% endblock %}

templates/employee_profile.html
{% extends "base.html" %}

{% block content %}
    <h1 class="mt-5">{{ full_name }}</h1>
    <p class="lead"><code>Age:</code> {{ age }}</p>
    <p class="lead"><code>Description:</code> {{ description }}</p>
    <p class="lead"><code>Department:</code><a href="{% url 'department_profile' department.id %}">{{ department.name }}</a></p> 
{% endblock %}

templates/employees.html
{% extends "base.html" %}

{% block content %}
    <h1 class="mt-5">Работники</h1>
    <div class="row">
        {% for employee in employees %}
            <div class="col-sm-4">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">{{ employee.first_name }}</h5>
                        <p class="card-text">{{ employee.description }}</p>
                        <a href="{% url 'employee_profile' employee.id %}" class="btn btn-primary">Перейти в профиль</a>
                        <p></p>
                        {% if employee.department %}
                            <a href="{% url 'department_profile' employee.department.id %}" class="btn btn-secondary">Отдел: {{ employee.department.name }}</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

templates/index.html
{% extends "base.html" %}